### ISSUE TITLE
[BUG] "Parse error" from json_serialization.gd on Exported projects

### ISSUE THREAD

**Issue by arran-nz** [neth392/godot-json#4]
Hey there,

Great library, I really like the way it's designed and have enjoyed using it - Thanks!

If I find a solution I may open a PR, would love to hear your thoughts. 

---

**Godot version:**

`Godot Engine v4.3.stable.official.77dcf97d8`

**Describe the bug**

On exported projects, the following error is output.
```
SCRIPT ERROR: Parse Error: Identifier "EditorInterface" not declared in the current scope.
          at: GDScript::reload (res://addons/godot-improved-json/serialize/json_serialization.gd:169)
SCRIPT ERROR: Parse Error: Identifier "EditorInterface" not declared in the current scope.
          at: GDScript::reload (res://addons/godot-improved-json/serialize/json_serialization.gd:170)
ERROR: Failed to load script "res://addons/godot-improved-json/serialize/json_serialization.gd" with error "Parse error".
```

**To Reproduce**

Export a project using the `JSONSerialization` node

**Additional context**

Commenting out / removing the offending imports in `json_serialization.gd` remedies the issue on export.

```
# In editor; handle ProjectSettings for object config registry
	if Engine.is_editor_hint() && JSONSerialization == self:
		# Create the setting if it does not exist
		if !ProjectSettings.has_setting(_SETTING_PATH):
			ProjectSettings.set_setting(_SETTING_PATH, _DEFAULT_REGISTRY_PATH)
		
		# Set the initial values & info for it every time
		ProjectSettings.set_initial_value(_SETTING_PATH, _DEFAULT_REGISTRY_PATH)
		ProjectSettings.set_as_basic(_SETTING_PATH, true)
		ProjectSettings.add_property_info({
			"name": _SETTING_PATH,
			"type": TYPE_STRING,
			"hint": PROPERTY_HINT_FILE,
			"hint_string": "*.tres"
		})
		# Cache the registry path to detect changes
		_registry_path_cache = _registry_path
		# Connect to changes
		ProjectSettings.settings_changed.connect(_on_project_settings_changed)
		
		EditorInterface.get_file_system_dock().files_moved.connect(_on_file_moved)
		EditorInterface.get_file_system_dock().file_removed.connect(_on_file_removed)
```

**Comment by neth392** [comment]
Thanks for the report! Haven't gotten to exporting a project yet in Godot myself (just been down addon rabbit holes) so didn't find this one in testing.

I'll work on a fix now and update this once published.

**Comment by neth392** [comment]
@arran-nz Should be fixed but I don't have any exportable projects to test it with currently, could you do me a favor and test the 1.2.1 release before I publish it to the AssetLib? Thanks!

**Comment by arran-nz** [comment]
That was quick! Just pulled and tested 49b1ea85d1140fe037af21ffab6a8fab5ed6c365 and it works for my exported project! Thank you :D
